version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo "Building Lambda functions..."
      - zip -r lambda-deployment.zip .
artifacts:
  files:
    - lambda-deployment.zip
