version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt -t ./package
  build:
    commands:
      - cp lambda_function.py ./package/
      - cd package && zip -r ../search-photos.zip .
artifacts:
  files:
    - search-photos.zip
